apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-w1dq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-w1dq@sha256:7f5da840bc9d03c9bb474dc983457d01b014e34075d76ffe0393dbc10ae723d4
        name: my-nodejs
        resources: {}
status: {}
